<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>False</IsPackable>
		<EnableMicrosoftTestingPlatform>True</EnableMicrosoftTestingPlatform>
	</PropertyGroup>

	<PropertyGroup>
		<!-- SYSLIB1045: Use 'GeneratedRegexAttribute' - not necessary for tests -->
		<NoWarn>SYSLIB1045</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Domain\Domain.csproj" />
		<ProjectReference Include="..\Testing.Common\Testing.Common.csproj" />
	</ItemGroup>

</Project>
