<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- For greater portability, here you can set TargetFrameworks to LTS+netstandard2.0, and LangVersion to Latest -->
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Version>0.1.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<!-- IDE0290: Use primary constructor - constuctor summaries tend to be useful in contracts -->
		<NoWarn>IDE0290</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="__ToDoAreaName__.__ToDoBoundedContextName__.Application" />
	</ItemGroup>

</Project>
