global using Architect.EntityFramework.DbContextManagement;
global using Microsoft.EntityFrameworkCore;
global using __ToDoAreaName__.__ToDoBoundedContextName__.Domain.Shared;
global using __ToDoAreaName__.__ToDoBoundedContextName__.Infrastructure.Databases.Shared;
global using __ToDoAreaName__.__ToDoBoundedContextName__.Infrastructure.Databases.Shared.Conventions;
global using __ToDoAreaName__.__ToDoBoundedContextName__.Infrastructure.Databases.Shared.Converters;
